### Intuition:
- Considered Algorithms:
  - Linear Kernel
  - Cosine Similarity

* Word to Vector Algorithms:
  * TF-IDF Vectorizer
  * Count Vectorizer

# Importing required libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

import warnings
warnings.filterwarnings("ignore")

### Loading Dataset

In [2]:
FILEPATH="../data/train/"

df = pd.read_csv(FILEPATH+"meta_data.csv")

In [3]:
df.head()

,title,meta_tags
0,Avatar,action adventure fantasy science fiction cultu...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...
2,Spectre,action adventure crime spy based on novel secr...
3,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,John Carter,action adventure science fiction based on nove...


In [4]:
df.isnull().sum()

title        0
meta_tags    0
dtype: int64

## Word to Vector

### TF-IDF Vectorizer

In [5]:
tf_idf_obj = TfidfVectorizer()
tfvt = tf_idf_obj.fit_transform(df['meta_tags'])

In [6]:
pd.DataFrame(tfvt.toarray(), columns=tf_idf_obj.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zorro,zuckerberg,zula,zurich,zuzu,zyklon,γη,卧底肥妈,绝地奶霸,超级妈妈
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


### CountVectorizer

In [7]:
cv_obj = CountVectorizer(analyzer='word', lowercase=True, stop_words='english')
cvt = cv_obj.fit_transform(df['meta_tags'])

In [8]:
pd.DataFrame(cvt.toarray(), columns=cv_obj.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zorro,zuckerberg,zula,zurich,zuzu,zyklon,γη,卧底肥妈,绝地奶霸,超级妈妈
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4800,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4801,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


### Intuition:
#### We should use TF-IDF Vectorizer with Linear Kernel algorithm because:
- Linear Kernel is faster compared to cosine similarity algorithm but the trade-off is it does not perform L2 regularization. So, as a countermeasure we should use TF-IDF Vectorizer with Linear Kernel because TF-IDF performs L2 regularization.

#### We should use Count Vectorizer with Cosine Similarity algorithm because:
- Cosine similarity inherently perform L2 regularization, as a result it is slower as compared to Linear Kernel. On the other hand, Count Vectorizer do not perform L2 regularization. So, there two are good match for each other.

#### Linear Kernel with TF-IDF Vectorizer is always preferable when the dataset is huge. But in that case before performing TF-IDF vectorization we should perform more accurate meta-data composition to get good similarity scores.

# Method-1: using Linear Kernel with TfidfVectorizer

In [9]:
similarity_matrix_lk = linear_kernel(tfvt, tfvt)
similarity_matrix_lk

array([[1.        , 0.02058947, 0.01950882, ..., 0.02263226, 0.00418546,
        0.        ],
       [0.02058947, 1.        , 0.01987093, ..., 0.02899363, 0.        ,
        0.0059537 ],
       [0.01950882, 0.01987093, 1.        , ..., 0.01584896, 0.        ,
        0.        ],
       ...,
       [0.02263226, 0.02899363, 0.01584896, ..., 1.        , 0.02063465,
        0.03393385],
       [0.00418546, 0.        , 0.        , ..., 0.02063465, 1.        ,
        0.03022913],
       [0.        , 0.0059537 , 0.        , ..., 0.03393385, 0.03022913,
        1.        ]], shape=(4803, 4803))

In [10]:
similarity_matrix_lk[0]

array([1.        , 0.02058947, 0.01950882, ..., 0.02263226, 0.00418546,
       0.        ], shape=(4803,))

### Testing

In [11]:
movie_title = "John Carter"

In [12]:
try:
    print(df.loc[df["title"] == movie_title].index[0])
except IndexError:
    print("Movie not found")

4


In [13]:
idx1 = df.loc[df["title"] == movie_title].index[0]

In [14]:
similarity_scores1 = list(enumerate(similarity_matrix_lk[idx1]))
similarity_scores1

[(0, np.float64(0.21837177908295544)),
 (1, np.float64(0.0425564224101914)),
 (2, np.float64(0.027709502255834545)),
 (3, np.float64(0.009141308678371426)),
 (4, np.float64(1.0)),
 (5, np.float64(0.02555240391004328)),
 (6, np.float64(0.028167442431043698)),
 (7, np.float64(0.07628992159593384)),
 (8, np.float64(0.00484892351264347)),
 (9, np.float64(0.025731729415188823)),
 (10, np.float64(0.08994163456990156)),
 (11, np.float64(0.010808915399304451)),
 (12, np.float64(0.05895681466344285)),
 (13, np.float64(0.011686767573958527)),
 (14, np.float64(0.09023591253191414)),
 (15, np.float64(0.03144546434967247)),
 (16, np.float64(0.07593355214224291)),
 (17, np.float64(0.06455653655014135)),
 (18, np.float64(0.09219455232522032)),
 (19, np.float64(0.04538456868527101)),
 (20, np.float64(0.018741847580870073)),
 (21, np.float64(0.042288041860381896)),
 (22, np.float64(0.03224755250545923)),
 (23, np.float64(0.027498626050663007)),
 (24, np.float64(0.04587387786405625)),
 (25, np.float64(0

In [15]:
similarity_scores1 = sorted(similarity_scores1, key=lambda x: x[1], reverse=True)
similarity_scores1

[(4, np.float64(1.0)),
 (373, np.float64(0.2924522182020951)),
 (487, np.float64(0.24232909219506604)),
 (270, np.float64(0.22336228036126748)),
 (0, np.float64(0.21837177908295544)),
 (473, np.float64(0.21704442625661668)),
 (778, np.float64(0.19004216074766256)),
 (141, np.float64(0.17093228926885634)),
 (1201, np.float64(0.16082432779344413)),
 (207, np.float64(0.15950633003233078)),
 (754, np.float64(0.15892089750534483)),
 (3668, np.float64(0.1554443447112357)),
 (2964, np.float64(0.15534516124253708)),
 (1198, np.float64(0.15217474796304847)),
 (260, np.float64(0.1501257762643834)),
 (91, np.float64(0.15011194623573346)),
 (1068, np.float64(0.1486110516457408)),
 (278, np.float64(0.1363541009502649)),
 (1768, np.float64(0.1350733451236379)),
 (581, np.float64(0.1342128206352034)),
 (1319, np.float64(0.13349691161539223)),
 (1326, np.float64(0.13217905145740938)),
 (3904, np.float64(0.1269635528599881)),
 (539, np.float64(0.12676866096017353)),
 (1415, np.float64(0.125792495001835

In [16]:
# top 5 similarities
movies_indices1 = [tpl[0] for tpl in similarity_scores1[1:6]]
scores_list1 = [f"{round(tpl[1],3)*100}%" for tpl in similarity_scores1[1:6]]
print(movies_indices1)
print(scores_list1)
df["title"].iloc[movies_indices1]

[373, 487, 270, 0, 473]
['29.2%', '24.2%', '22.3%', '21.8%', '21.7%']


373    Mission to Mars
487         Red Planet
270        The Martian
0               Avatar
473      Mars Attacks!
Name: title, dtype: object

# Method-2: using Cosine Similarity with CountVectorizer

In [17]:
similarity_matrix_cs = cosine_similarity(cvt,cvt)
similarity_matrix_cs

array([[1.        , 0.0727393 , 0.05270463, ..., 0.05986843, 0.01937461,
        0.        ],
       [0.0727393 , 1.        , 0.04600437, ..., 0.09798273, 0.        ,
        0.        ],
       [0.05270463, 0.04600437, 1.        , ..., 0.03786412, 0.        ,
        0.        ],
       ...,
       [0.05986843, 0.09798273, 0.03786412, ..., 1.        , 0.06263608,
        0.03966818],
       [0.01937461, 0.        , 0.        , ..., 0.06263608, 1.        ,
        0.05134962],
       [0.        , 0.        , 0.        , ..., 0.03966818, 0.05134962,
        1.        ]], shape=(4803, 4803))

In [18]:
similarity_matrix_cs[0]

array([1.        , 0.0727393 , 0.05270463, ..., 0.05986843, 0.01937461,
       0.        ], shape=(4803,))

### Testing

In [19]:
movie_title = "John Carter"
idx2 = df.loc[df["title"] == movie_title].index[0]
similarity_scores2 = list(enumerate(similarity_matrix_cs[idx2]))
similarity_scores2 = sorted(similarity_scores2, key=lambda x: x[1], reverse=True)

In [20]:
# top 5 similarities
movies_indices2 = [tpl[0] for tpl in similarity_scores2[1:6]]
scores_list2 = [f"{round(tpl[1],3)*100}%" for tpl in similarity_scores2[1:6]]
print(movies_indices2)
print(scores_list2)
df["title"].iloc[movies_indices2]

[373, 0, 260, 270, 581]
['31.900000000000002%', '31.900000000000002%', '28.1%', '28.1%', '27.0%']


373            Mission to Mars
0                       Avatar
260               Ender's Game
270                The Martian
581    Star Trek: Insurrection
Name: title, dtype: object

### Comparison:
- Comparing performance of both algorithms for same input

In [21]:
def get_similar_movies_lk(movie_title):
    idx = df.loc[df["title"] == movie_title].index[0]
    scores = list(enumerate(similarity_matrix_lk[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    movies_indices = [tpl[0] for tpl in scores[1:6]]
    similarity_scores = [f"{round(tpl[1],3)*100}%" for tpl in scores[1:6]]

    similar_movie_list = list(df["title"].iloc[movies_indices])
    return similar_movie_list,similarity_scores


def get_similar_movies_cs(movie_title):
    idx = df.loc[df["title"] == movie_title].index[0]
    scores = list(enumerate(similarity_matrix_cs[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    movies_indices = [tpl[0] for tpl in scores[1:6]]
    similarity_scores = [f"{round(tpl[1],3)*100}%" for tpl in scores[1:6]]

    similar_movie_list = list(df["title"].iloc[movies_indices])
    return similar_movie_list,similarity_scores

In [24]:
try:
    movie_title = input("Enter your favorite movie: ").strip()
    print("\nTop 5 matches using Linear Kernel:")
    movies, similar = get_similar_movies_lk(movie_title)
    for i, movie in enumerate(movies):
        print("{} --> with {} similarity".format(movie, similar[i]))

    print("\nTop5 matches using Cosine Similarity:")
    movies, similar = get_similar_movies_cs(movie_title)
    for i, movie in enumerate(movies):
        print("{} --> with {} similarity".format(movie, similar[i]))
except IndexError:
    print("No such movie found in the dataset")


Top 5 matches using Linear Kernel:
Aliens --> with 33.7% similarity
Alien³ --> with 30.7% similarity
Mission to Mars --> with 29.9% similarity
Moonraker --> with 27.500000000000004% similarity
Spaceballs --> with 26.900000000000002% similarity

Top5 matches using Cosine Similarity:
Aliens --> with 44.1% similarity
Mission to Mars --> with 42.1% similarity
Alien³ --> with 41.4% similarity
Silent Running --> with 39.2% similarity
Moonraker --> with 38.9% similarity


# Cosine similarity is performing better